### ISSUE TITLE
gr-baz blocks are not available

### ISSUE THREAD

**Issue by bibor** [bibor/signal-tools-container#1]
If a gr-baz is executed python throws an ImportError.

```
Traceback (most recent call last):
  File "/home/signals/top_block.py", line 20, in <module>
    from baz import baudline
  File "/usr/local/lib/python2.7/dist-packages/baz/__init__.py", line 40, in <module>
    from baz_swig import *
ImportError: No module named baz_swig
```

**Comment by bibor** [comment]
fixed in baz
